server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

spring:
  application:
    name: carsystem
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
      
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/carsystem
    username: postgres
    password: postgres
    
jwt:
  config:
    type: encripted
          
          
          
    